blogTitle = "effulgence // prayash thapa"
mastHead = "effulgence // prayash thapa"
authorName = "Prayash Thapa"
shortName = "effulgence"
linkPrefix = ""
domain = "http://effulgence.io"
email = "prayash@effulgence.io"
description = "Hi, I'm Prayash. I make music and write code that draws things."
