var tracks = [
  {
    kind: 'track',
    id: 274242735,
    created_at: '2016/07/18 16:12:15 +0000',
    user_id: 1041317,
    duration: 326481,
    commentable: true,
    state: 'finished',
    original_content_size: 57577004,
    last_modified: '2016/07/19 03:53:56 +0000',
    sharing: 'public',
    tag_list:
      'acoustic electroacoustic guitar fingerstyle ambient chillout downtempo',
    permalink: 'itsus',
    streamable: true,
    embeddable_by: 'all',
    purchase_url: null,
    purchase_title: null,
    label_id: null,
    genre: 'Electronic',
    title: 'Us',
    description:
      'An ode to the wonders of companionship.\nCheck out the video here: https://youtu.be/lKzFU30NyK8\n\nThank you for listening. :)',
    label_name: null,
    release: null,
    track_type: null,
    key_signature: null,
    isrc: null,
    video_url: null,
    bpm: null,
    release_year: 2016,
    release_month: 7,
    release_day: 17,
    original_format: 'wav',
    license: 'cc-by',
    uri: 'https://api.soundcloud.com/tracks/274242735',
    user: {
      id: 1041317,
      kind: 'user',
      permalink: 'effulgence',
      username: 'Effulgence.',
      last_modified: '2017/02/13 06:51:16 +0000',
      uri: 'https://api.soundcloud.com/users/1041317',
      permalink_url: 'http://soundcloud.com/effulgence',
      avatar_url: 'https://i1.sndcdn.com/avatars-000212664323-ngpb4u-large.jpg'
    },
    permalink_url: 'https://soundcloud.com/effulgence/itsus',
    artwork_url: 'https://i1.sndcdn.com/artworks-000172119017-djpgcd-large.jpg',
    stream_url: 'https://api.soundcloud.com/tracks/274242735/stream',
    download_url: 'https://api.soundcloud.com/tracks/274242735/download',
    playback_count: 3864,
    download_count: 0,
    favoritings_count: 115,
    reposts_count: 9,
    comment_count: 7,
    downloadable: false,
    waveform_url: 'https://w1.sndcdn.com/sbJO13GQWNcj_m.png',
    attachments_uri: 'https://api.soundcloud.com/tracks/274242735/attachments'
  },
  {
    kind: 'track',
    id: 212036547,
    created_at: '2015/06/26 04:19:25 +0000',
    user_id: 1041317,
    duration: 150112,
    commentable: true,
    state: 'finished',
    original_content_size: 6071555,
    last_modified: '2015/10/11 21:49:48 +0000',
    sharing: 'public',
    tag_list:
      'Electronic Guitar Acoustic Electric Beatbox Modern Viola "Prayash Thapa" "Jake Quattlebaum"',
    permalink: 'stray-thoughts',
    streamable: true,
    embeddable_by: 'all',
    purchase_url: null,
    purchase_title: null,
    label_id: null,
    genre: 'Electroacoustic',
    title: 'Stray Thoughts...',
    description:
      '"Life can be noisy sometimes but there\'s music in it if you pay attention to what matters." - Plini the Elder\n- - -\nMassive thanks to the homie Jake Quattlebaum for the viola lines!',
    label_name: null,
    release: null,
    track_type: null,
    key_signature: null,
    isrc: null,
    video_url: null,
    bpm: null,
    release_year: null,
    release_month: null,
    release_day: null,
    original_format: 'mp3',
    license: 'cc-by',
    uri: 'https://api.soundcloud.com/tracks/212036547',
    user: {
      id: 1041317,
      kind: 'user',
      permalink: 'effulgence',
      username: 'Effulgence.',
      last_modified: '2017/02/13 06:51:16 +0000',
      uri: 'https://api.soundcloud.com/users/1041317',
      permalink_url: 'http://soundcloud.com/effulgence',
      avatar_url: 'https://i1.sndcdn.com/avatars-000212664323-ngpb4u-large.jpg'
    },
    permalink_url: 'https://soundcloud.com/effulgence/stray-thoughts',
    artwork_url: 'https://i1.sndcdn.com/artworks-000121394845-s3nouv-large.jpg',
    stream_url: 'https://api.soundcloud.com/tracks/212036547/stream',
    download_url: 'https://api.soundcloud.com/tracks/212036547/download',
    playback_count: 12432,
    download_count: 0,
    favoritings_count: 209,
    reposts_count: 47,
    comment_count: 17,
    downloadable: false,
    waveform_url: 'https://w1.sndcdn.com/Jxgrzt8iet0B_m.png',
    attachments_uri: 'https://api.soundcloud.com/tracks/212036547/attachments'
  },
  {
    kind: 'track',
    id: 207170160,
    created_at: '2015/05/25 19:10:07 +0000',
    user_id: 1041317,
    duration: 157898,
    commentable: true,
    state: 'finished',
    original_content_size: 41761136,
    last_modified: '2015/09/10 06:48:50 +0000',
    sharing: 'public',
    tag_list:
      'Effulgence "An Arrival" Chill Ambient Guitar Fingerstyle Acoustic',
    permalink: 'an-arrival',
    streamable: true,
    embeddable_by: 'all',
    purchase_url: 'http://effulgence.bandcamp.com/album/an-arrival',
    purchase_title: null,
    label_id: null,
    genre: 'Electroacoustic',
    title: 'An Arrival',
    description:
      'On April 25th, 2015 my homeland Nepal was devastated by a 7.8M Earthquake which left many families homeless. For every purchase of this track, I will match the exact amount from my own personal funds to contribute towards direct local relief.\n\nhttp://effulgence.bandcamp.com/album/an-arrival',
    label_name: null,
    release: null,
    track_type: null,
    key_signature: null,
    isrc: null,
    video_url: null,
    bpm: null,
    release_year: null,
    release_month: null,
    release_day: null,
    original_format: 'wav',
    license: 'cc-by',
    uri: 'https://api.soundcloud.com/tracks/207170160',
    user: {
      id: 1041317,
      kind: 'user',
      permalink: 'effulgence',
      username: 'Effulgence.',
      last_modified: '2017/02/13 06:51:16 +0000',
      uri: 'https://api.soundcloud.com/users/1041317',
      permalink_url: 'http://soundcloud.com/effulgence',
      avatar_url: 'https://i1.sndcdn.com/avatars-000212664323-ngpb4u-large.jpg'
    },
    permalink_url: 'https://soundcloud.com/effulgence/an-arrival',
    artwork_url: 'https://i1.sndcdn.com/artworks-000118011810-ap87kc-large.jpg',
    stream_url: 'https://api.soundcloud.com/tracks/207170160/stream',
    download_url: 'https://api.soundcloud.com/tracks/207170160/download',
    playback_count: 7770,
    download_count: 3,
    favoritings_count: 167,
    reposts_count: 27,
    comment_count: 14,
    downloadable: false,
    waveform_url: 'https://w1.sndcdn.com/BnfgtuPczrG3_m.png',
    attachments_uri: 'https://api.soundcloud.com/tracks/207170160/attachments'
  },
  {
    kind: 'track',
    id: 154034372,
    created_at: '2014/06/12 13:36:54 +0000',
    user_id: 1041317,
    duration: 235777,
    commentable: true,
    state: 'finished',
    original_content_size: 9429158,
    last_modified: '2016/07/10 15:09:45 +0000',
    sharing: 'public',
    tag_list:
      'Effulgence Distance Illumine EP Chill Acoustic Anime Guitar Fingerstyle Downtempo',
    permalink: 'distance-3',
    streamable: true,
    embeddable_by: 'all',
    purchase_url: 'http://effulgence.bandcamp.com/album/illumine-ep',
    purchase_title: 'Free Download',
    label_id: null,
    genre: 'Electroacoustic',
    title: 'Distance',
    description:
      'Inspired by \'5 Centimeters Per Second".\nViolin by my friend Christen Neugebauer. :)',
    label_name: '',
    release: '',
    track_type: 'original',
    key_signature: '',
    isrc: null,
    video_url: null,
    bpm: null,
    release_year: null,
    release_month: null,
    release_day: null,
    original_format: 'mp3',
    license: 'all-rights-reserved',
    uri: 'https://api.soundcloud.com/tracks/154034372',
    user: {
      id: 1041317,
      kind: 'user',
      permalink: 'effulgence',
      username: 'Effulgence.',
      last_modified: '2017/02/13 06:51:16 +0000',
      uri: 'https://api.soundcloud.com/users/1041317',
      permalink_url: 'http://soundcloud.com/effulgence',
      avatar_url: 'https://i1.sndcdn.com/avatars-000212664323-ngpb4u-large.jpg'
    },
    permalink_url: 'https://soundcloud.com/effulgence/distance-3',
    artwork_url: 'https://i1.sndcdn.com/artworks-000127032971-0yysml-large.jpg',
    stream_url: 'https://api.soundcloud.com/tracks/154034372/stream',
    download_url: 'https://api.soundcloud.com/tracks/154034372/download',
    playback_count: 24262,
    download_count: 0,
    favoritings_count: 455,
    reposts_count: 68,
    comment_count: 41,
    downloadable: false,
    waveform_url: 'https://w1.sndcdn.com/iI5zP7gci01E_m.png',
    attachments_uri: 'https://api.soundcloud.com/tracks/154034372/attachments'
  },
  {
    kind: 'track',
    id: 153624316,
    created_at: '2014/06/09 23:23:17 +0000',
    user_id: 1041317,
    duration: 245233,
    commentable: true,
    state: 'finished',
    original_content_size: 9811655,
    last_modified: '2015/09/10 06:48:50 +0000',
    sharing: 'public',
    tag_list: 'Effulgence "Illumine EP" Transience Electronic Guitar Ambient',
    permalink: 'transience',
    streamable: true,
    embeddable_by: 'all',
    purchase_url: 'http://effulgence.bandcamp.com/album/illumine-ep',
    purchase_title: 'Free Download',
    label_id: null,
    genre: 'Electroacoustic',
    title: 'Transience',
    description: 'Track 4 off Illumine EP.',
    label_name: '',
    release: '',
    track_type: 'original',
    key_signature: '',
    isrc: null,
    video_url: null,
    bpm: null,
    release_year: null,
    release_month: null,
    release_day: null,
    original_format: 'mp3',
    license: 'all-rights-reserved',
    uri: 'https://api.soundcloud.com/tracks/153624316',
    user: {
      id: 1041317,
      kind: 'user',
      permalink: 'effulgence',
      username: 'Effulgence.',
      last_modified: '2017/02/13 06:51:16 +0000',
      uri: 'https://api.soundcloud.com/users/1041317',
      permalink_url: 'http://soundcloud.com/effulgence',
      avatar_url: 'https://i1.sndcdn.com/avatars-000212664323-ngpb4u-large.jpg'
    },
    permalink_url: 'https://soundcloud.com/effulgence/transience',
    artwork_url: 'https://i1.sndcdn.com/artworks-000127032978-35ixic-large.jpg',
    stream_url: 'https://api.soundcloud.com/tracks/153624316/stream',
    download_url: 'https://api.soundcloud.com/tracks/153624316/download',
    playback_count: 16474,
    download_count: 0,
    favoritings_count: 264,
    reposts_count: 40,
    comment_count: 14,
    downloadable: false,
    waveform_url: 'https://w1.sndcdn.com/RVzT3cZ9iA3C_m.png',
    attachments_uri: 'https://api.soundcloud.com/tracks/153624316/attachments'
  },
  {
    kind: 'track',
    id: 152634049,
    created_at: '2014/06/03 16:45:31 +0000',
    user_id: 1041317,
    duration: 218247,
    commentable: true,
    state: 'finished',
    original_content_size: 38489242,
    last_modified: '2015/09/10 06:48:50 +0000',
    sharing: 'public',
    tag_list:
      'Effulgence "Images of Essence" Fingerstyle Guitar Glitch "Illumine EP"',
    permalink: 'images-of-essence',
    streamable: true,
    embeddable_by: 'all',
    purchase_url: 'http://effulgence.bandcamp.com/album/illumine-ep',
    purchase_title: 'Free Download',
    label_id: null,
    genre: 'Electroacoustic',
    title: 'Images Of Essence',
    description:
      '2nd track from my upcoming Illumine EP.\r\nSpecial thanks to Kayla Mullen for her voice and Christen Neugebauer for the snippet of violin!\r\n\r\nMastered by https://soundcloud.com/benwaa.',
    label_name: '',
    release: '',
    track_type: 'original',
    key_signature: '',
    isrc: null,
    video_url: null,
    bpm: null,
    release_year: null,
    release_month: null,
    release_day: null,
    original_format: 'wav',
    license: 'cc-by',
    uri: 'https://api.soundcloud.com/tracks/152634049',
    user: {
      id: 1041317,
      kind: 'user',
      permalink: 'effulgence',
      username: 'Effulgence.',
      last_modified: '2017/02/13 06:51:16 +0000',
      uri: 'https://api.soundcloud.com/users/1041317',
      permalink_url: 'http://soundcloud.com/effulgence',
      avatar_url: 'https://i1.sndcdn.com/avatars-000212664323-ngpb4u-large.jpg'
    },
    permalink_url: 'https://soundcloud.com/effulgence/images-of-essence',
    artwork_url: 'https://i1.sndcdn.com/artworks-000117172029-teh26p-large.jpg',
    stream_url: 'https://api.soundcloud.com/tracks/152634049/stream',
    download_url: 'https://api.soundcloud.com/tracks/152634049/download',
    playback_count: 3483,
    download_count: 0,
    favoritings_count: 92,
    reposts_count: 15,
    comment_count: 15,
    downloadable: false,
    waveform_url: 'https://w1.sndcdn.com/ezQ6rom9tEr5_m.png',
    attachments_uri: 'https://api.soundcloud.com/tracks/152634049/attachments'
  },
  {
    kind: 'track',
    id: 135173097,
    created_at: '2014/02/16 20:47:50 +0000',
    user_id: 1041317,
    duration: 240139,
    commentable: true,
    state: 'finished',
    original_content_size: 9607898,
    last_modified: '2015/11/18 00:29:54 +0000',
    sharing: 'public',
    tag_list: 'Effulgence Illumine EP Prayash Thapa Guitar',
    permalink: 'illumine',
    streamable: true,
    embeddable_by: 'all',
    purchase_url: 'http://effulgence.bandcamp.com/album/illumine-ep',
    purchase_title: 'Free Download',
    label_id: null,
    genre: 'Electroacoustic',
    title: 'Illumine',
    description:
      'Here is the title track for my upcoming EP, Illumine.\r\nSpeech sample by Dr. Neil DeGrasse Tyson & Amelia June.\r\n\r\nMastered by soundcloud.com/benwaa',
    label_name: '',
    release: '',
    track_type: 'original',
    key_signature: '',
    isrc: null,
    video_url: null,
    bpm: null,
    release_year: null,
    release_month: null,
    release_day: null,
    original_format: 'mp3',
    license: 'cc-by',
    uri: 'https://api.soundcloud.com/tracks/135173097',
    user: {
      id: 1041317,
      kind: 'user',
      permalink: 'effulgence',
      username: 'Effulgence.',
      last_modified: '2017/02/13 06:51:16 +0000',
      uri: 'https://api.soundcloud.com/users/1041317',
      permalink_url: 'http://soundcloud.com/effulgence',
      avatar_url: 'https://i1.sndcdn.com/avatars-000212664323-ngpb4u-large.jpg'
    },
    permalink_url: 'https://soundcloud.com/effulgence/illumine',
    artwork_url: 'https://i1.sndcdn.com/artworks-000080492302-gnm385-large.jpg',
    stream_url: 'https://api.soundcloud.com/tracks/135173097/stream',
    download_url: 'https://api.soundcloud.com/tracks/135173097/download',
    playback_count: 24532,
    download_count: 410,
    favoritings_count: 552,
    reposts_count: 105,
    comment_count: 64,
    downloadable: false,
    waveform_url: 'https://w1.sndcdn.com/x66T97huWNzm_m.png',
    attachments_uri: 'https://api.soundcloud.com/tracks/135173097/attachments'
  },
  {
    kind: 'track',
    id: 78467206,
    created_at: '2013/02/09 03:31:26 +0000',
    user_id: 1041317,
    duration: 313523,
    commentable: true,
    state: 'finished',
    original_content_size: 12543064,
    last_modified: '2014/02/15 05:03:41 +0000',
    sharing: 'public',
    tag_list:
      'effulgence immensus a heaven in wild flower chill downtempo idm ambient guitars william blake auguries of innocence colorado boulder',
    permalink: 'heaven',
    streamable: true,
    embeddable_by: 'all',
    purchase_url: null,
    purchase_title: null,
    label_id: null,
    genre: 'Electroacoustic',
    title: 'Effulgence & Immensus - A Heaven in a Wild Flower',
    description:
      'To see a world in a grain of sand\r\nAnd a heaven in a wild flower,\r\nHold infinity in the palm of your hand,\r\nAnd eternity in an hour.\r\n___________________\r\n\r\nA collaboration between me and http://soundcloud.com/immensus (he makes excellent melodic music - check his work!)\r\nHope you enjoy. :)',
    label_name: '',
    release: '',
    track_type: 'original',
    key_signature: '',
    isrc: null,
    video_url: null,
    bpm: null,
    release_year: null,
    release_month: null,
    release_day: null,
    original_format: 'mp3',
    license: 'cc-by',
    uri: 'https://api.soundcloud.com/tracks/78467206',
    user: {
      id: 1041317,
      kind: 'user',
      permalink: 'effulgence',
      username: 'Effulgence.',
      last_modified: '2017/02/13 06:51:16 +0000',
      uri: 'https://api.soundcloud.com/users/1041317',
      permalink_url: 'http://soundcloud.com/effulgence',
      avatar_url: 'https://i1.sndcdn.com/avatars-000212664323-ngpb4u-large.jpg'
    },
    permalink_url: 'https://soundcloud.com/effulgence/heaven',
    artwork_url: 'https://i1.sndcdn.com/artworks-000040342803-yd7g1t-large.jpg',
    stream_url: 'https://api.soundcloud.com/tracks/78467206/stream',
    download_url: 'https://api.soundcloud.com/tracks/78467206/download',
    playback_count: 6357,
    download_count: 289,
    favoritings_count: 129,
    reposts_count: 21,
    comment_count: 52,
    downloadable: true,
    waveform_url: 'https://w1.sndcdn.com/t6nGf99v3mtg_m.png',
    attachments_uri: 'https://api.soundcloud.com/tracks/78467206/attachments'
  },
  {
    kind: 'track',
    id: 43176895,
    created_at: '2012/04/15 05:30:44 +0000',
    user_id: 1041317,
    duration: 321637,
    commentable: true,
    state: 'finished',
    original_content_size: 14524201,
    last_modified: '2016/02/15 00:41:43 +0000',
    sharing: 'public',
    tag_list: 'effulgence stillness prayash thapa',
    permalink: 'stillness',
    streamable: true,
    embeddable_by: 'all',
    purchase_url: null,
    purchase_title: null,
    label_id: null,
    genre: 'Electroacoustic',
    title: 'Stillness',
    description:
      'I aimed to make this piece as chilled out and immersing as possible. \r\n\r\nSampled speech by Eckhart Tolle in this video: http://www.youtube.com/watch?v=PkF4kA2ZT70\r\nField recording was just some random nature video on YouTube.\r\n\r\nI also had the honor to have this track featured on an Ambient Compilation album by PegasiaMusic! You check it out here:\r\nhttp://pegasiamusic.com/2012/06/16/pegasiamusic014-faint-young-sun/',
    label_name: '',
    release: '',
    track_type: 'original',
    key_signature: '',
    isrc: null,
    video_url: null,
    bpm: null,
    release_year: null,
    release_month: null,
    release_day: null,
    original_format: 'mp3',
    license: 'cc-by',
    uri: 'https://api.soundcloud.com/tracks/43176895',
    user: {
      id: 1041317,
      kind: 'user',
      permalink: 'effulgence',
      username: 'Effulgence.',
      last_modified: '2017/02/13 06:51:16 +0000',
      uri: 'https://api.soundcloud.com/users/1041317',
      permalink_url: 'http://soundcloud.com/effulgence',
      avatar_url: 'https://i1.sndcdn.com/avatars-000212664323-ngpb4u-large.jpg'
    },
    permalink_url: 'https://soundcloud.com/effulgence/stillness',
    artwork_url: 'https://i1.sndcdn.com/artworks-000147181617-py5cxj-large.jpg',
    stream_url: 'https://api.soundcloud.com/tracks/43176895/stream',
    download_url: 'https://api.soundcloud.com/tracks/43176895/download',
    playback_count: 3663,
    download_count: 146,
    favoritings_count: 70,
    reposts_count: 10,
    comment_count: 65,
    downloadable: true,
    waveform_url: 'https://w1.sndcdn.com/FrdPrautHYin_m.png',
    attachments_uri: 'https://api.soundcloud.com/tracks/43176895/attachments'
  },
  {
    kind: 'track',
    id: 36973362,
    created_at: '2012/02/17 21:56:12 +0000',
    user_id: 1041317,
    duration: 256228,
    commentable: true,
    state: 'finished',
    original_content_size: 10243133,
    last_modified: '2016/05/20 00:53:31 +0000',
    sharing: 'public',
    tag_list:
      'quantum entanglement prayash thapa idm ambient atmospheric e experimental melodic soothing meditative piano sine waves sub complex percussion glitches effulgence',
    permalink: 'quantum-entanglement',
    streamable: true,
    embeddable_by: 'all',
    purchase_url: null,
    purchase_title: null,
    label_id: null,
    genre: 'Electronic',
    title: 'Quantum Entanglement',
    description:
      'My attempt at combining IDM and Ambient elements. \r\nThe sample is from a speech by Gangaji. (http://www.youtube.com/watch?v=kUtH0DDJorM)\r\n<b>"When the question who is followed all the way back to its source, innocently, there is a huge astounding realization. There is no entity there at all, there is only the indefinable, boundless recognition of yourself as inseparable from anything else." </b>\r\n\r\nCredits go to http://soundcloud.com/paniono for the mastering. \r\n\r\nI had the honor of having this track released on the http://soundcloud.com/cosmiccore album on April 5th featuring 24 other artists all over the world with enormous amounts of talent. I highly recommend you to check it out as there will be more volumes released in the times to come. :)',
    label_name: '',
    release: '',
    track_type: 'original',
    key_signature: '',
    isrc: null,
    video_url: null,
    bpm: null,
    release_year: null,
    release_month: null,
    release_day: null,
    original_format: 'mp3',
    license: 'all-rights-reserved',
    uri: 'https://api.soundcloud.com/tracks/36973362',
    user: {
      id: 1041317,
      kind: 'user',
      permalink: 'effulgence',
      username: 'Effulgence.',
      last_modified: '2017/02/13 06:51:16 +0000',
      uri: 'https://api.soundcloud.com/users/1041317',
      permalink_url: 'http://soundcloud.com/effulgence',
      avatar_url: 'https://i1.sndcdn.com/avatars-000212664323-ngpb4u-large.jpg'
    },
    permalink_url: 'https://soundcloud.com/effulgence/quantum-entanglement',
    artwork_url: 'https://i1.sndcdn.com/artworks-000147181544-4ot6u4-large.jpg',
    stream_url: 'https://api.soundcloud.com/tracks/36973362/stream',
    download_url: 'https://api.soundcloud.com/tracks/36973362/download',
    playback_count: 2293,
    download_count: 143,
    favoritings_count: 46,
    reposts_count: 4,
    comment_count: 57,
    downloadable: true,
    waveform_url: 'https://w1.sndcdn.com/nHScLNFUxY2i_m.png',
    attachments_uri: 'https://api.soundcloud.com/tracks/36973362/attachments'
  }
]

export default tracks
